<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-21 08:48
=======
# Generated by Django 2.1.5 on 2019-03-21 18:25
>>>>>>> f510ab2cf4bf041356b1a8b61312b60e8006df10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.CharField(max_length=200)),
                ('url2', models.CharField(blank=True, max_length=200)),
                ('url3', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_date', models.DateField(verbose_name='project date')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
<<<<<<< HEAD
                ('teammate_role', models.TextField(max_length=100)),
=======
                ('teammate_role', models.TextField(blank=True, max_length=100)),
>>>>>>> f510ab2cf4bf041356b1a8b61312b60e8006df10
                ('feedback', models.TextField(max_length=250)),
                ('git_hub_link', models.CharField(max_length=250)),
                ('deployed_app_link', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cohort_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('review', models.TextField(max_length=250)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
=======
                ('pitchdeck_review', models.TextField(max_length=250, verbose_name='Pitch Deck Feedback')),
                ('pitchdeck_rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Pitch Deck Rating')),
                ('content_review', models.TextField(max_length=250, verbose_name='Content Feedback')),
                ('content_rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Content Rating')),
                ('UIUX_review', models.TextField(max_length=250, verbose_name='UI/UX Feedback')),
                ('UIUX_rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='UI/UX Rating')),
                ('clean_code_review', models.TextField(max_length=250, verbose_name='Code Feedback')),
                ('clean_code_rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Code Rating')),
                ('presentation_review', models.TextField(max_length=250, verbose_name='Presentation Feedback')),
                ('presentation_rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Presentation Rating')),
>>>>>>> f510ab2cf4bf041356b1a8b61312b60e8006df10
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech1', models.CharField(max_length=200)),
                ('tech2', models.CharField(blank=True, max_length=200)),
                ('tech3', models.CharField(blank=True, max_length=200)),
                ('tech4', models.CharField(blank=True, max_length=200)),
                ('tech5', models.CharField(blank=True, max_length=200)),
                ('tech6', models.CharField(blank=True, max_length=200)),
                ('tech7', models.CharField(blank=True, max_length=200)),
                ('tech8', models.CharField(blank=True, max_length=200)),
                ('tech9', models.CharField(blank=True, max_length=200)),
                ('tech10', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Project')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('cohort_date', models.DateField(verbose_name='cohort date')),
                ('git_hub_link', models.CharField(max_length=250)),
                ('linkedin_link', models.CharField(max_length=250)),
                ('portfolio_link', models.CharField(max_length=250)),
=======
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('cohort_date', models.DateField(verbose_name='cohort date')),
                ('git_hub_link', models.CharField(blank=True, max_length=250)),
                ('linkedin_link', models.CharField(blank=True, max_length=250)),
                ('portfolio_link', models.CharField(blank=True, max_length=250)),
                ('project', models.ManyToManyField(to='main_app.Project')),
>>>>>>> f510ab2cf4bf041356b1a8b61312b60e8006df10
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Project'),
        ),
    ]
