# Generated by Django 2.1.5 on 2019-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-cohort_date']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='spetialty',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='main_app.Project'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='cohort_date',
            field=models.DateField(verbose_name='cohort date'),
        ),
    ]
