# Generated by Django 2.1.7 on 2019-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teammate_role',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
