# Generated by Django 2.1.5 on 2019-03-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190319_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='user',
        ),
    ]
