# Generated by Django 2.1.5 on 2019-03-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('cohort_date', models.DateField(verbose_name='cohort date')),
                ('git_hub_link', models.CharField(blank=True, max_length=250)),
                ('linkedin_link', models.CharField(blank=True, max_length=250)),
                ('portfolio_link', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='url1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='role',
            new_name='teammate_role',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='tech_type',
        ),
        migrations.AddField(
            model_name='image',
            name='url2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='url3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='UIUX_rating',
            field=models.CharField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, max_length=5, verbose_name='UI/UX Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='UIUX_review',
            field=models.TextField(default=1, max_length=250, verbose_name='UI/UX Feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='clean_code_rating',
            field=models.CharField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, max_length=5, verbose_name='Code Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='clean_code_review',
            field=models.TextField(default=1, max_length=250, verbose_name='Code Feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='content_rating',
            field=models.CharField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, max_length=5, verbose_name='Content Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='content_review',
            field=models.TextField(default=1, max_length=250, verbose_name='Content Feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='pitchdeck_rating',
            field=models.CharField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, max_length=5, verbose_name='Pitch Deck Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='pitchdeck_review',
            field=models.TextField(default=1, max_length=250, verbose_name='Pitch Deck Feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='presentation_rating',
            field=models.CharField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, max_length=5, verbose_name='Presentation Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='presentation_review',
            field=models.TextField(default=1, max_length=250, verbose_name='Presentation Feedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='tech1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='tech10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='user_details',
            name='project',
            field=models.ManyToManyField(to='main_app.Project'),
        ),
    ]
