# Generated by Django 2.1.5 on 2019-03-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190320_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='UIUX_rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='UI/UX Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='clean_code_rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Code Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Content Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pitchdeck_rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Pitch Deck Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='presentation_rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Presentation Rating'),
        ),
    ]
